#General
server:
  port: 8080
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false
    path: /error

# Postgres connection settings
spring:
  datasource:
    url: jdbc:postgresql://localhost:1023/local_spring
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: example

    # HikariCP settings
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolBooks

  # Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  devtools:
    restart:
      enabled: false

# JPA settings
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: false
          batch_size: 15
      format_sql: true
      order_inserts: true
      generate_statistics: false
  show-sql: false
  ddl-auto: none
  generate-ddl: false

#Mail
  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    default-encoding: UTF-8
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

#PDF
pdf:
  output:
    dir: "reports"

#Spring Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true
    export:
      prometheus:
        enabled: true

#apis
api:
  viacep:
    enabled: true
    url: https://viacep.com.br
    endpoint: /ws/{cep}/json

  brasilApi:
    enabled: true
    url: https://brasilapi.com.br
    endpoint: /api/cep/v1/{cep}
