services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
      - "15692:15692" # Prometheus plugin
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_prometheus start"
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/log/rabbitmq
    networks:
      - monitoring_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring_net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: myStrongPassword
    command: >
      redis-server
      --requirepass myStrongPassword
      --databases 16
    volumes:
      - redis-data:/data
    restart: always


  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:5540"
    volumes:
      - redisinsight-data:/db
    depends_on:
      - redis

  flyway:
    image: flyway/flyway
    container_name: flyway
    env_file:
      - database.env
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ../src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "1023:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
      image: mailhog/mailhog
      container_name: mailhog
      ports:
        - "1025:1025" # SMTP port
        - "8025:8025" # Web interface port

volumes:
  postgres_data:
  redis-data:
  redisinsight-data:
  rabbitmq_data:
  rabbitmq_log:

networks:
  monitoring_net:
    driver: bridge

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "7999:8080"
#    depends_on:
#      - postgres