services:

  flyway:
    image: flyway/flyway
    env_file:
      - database.env
    command: -connectRetries=60 migrate
    volumes:
      - ../src/main/resources/db/migration:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "1023:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "7999:8080"
#    depends_on:
#      - postgres