# Use postgres/example user/password credentials
version: '3.1'

services:

  flyway:
    image: flyway/flyway
    env_file:
      - database.env
    command: -connectRetries=60 migrate
    volumes:
      - ../src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "1023:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - postgres