services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/log/rabbitmq

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: myStrongPassword
    command: >
      redis-server
      --requirepass myStrongPassword
      --databases 16
    volumes:
      - redis-data:/data
    restart: always


  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:5540"
    volumes:
      - redisinsight-data:/db
    depends_on:
      - redis

  flyway:
    image: flyway/flyway
    container_name: flyway
    env_file:
      - database.env
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ../src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - database.env
    ports:
      - "1023:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis-data:
  redisinsight-data:
  rabbitmq_data:
  rabbitmq_log:

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "7999:8080"
#    depends_on:
#      - postgres